---
apiVersion: v1
kind: Service
metadata:
  namespace: '2048'
  name: 'service-2048'
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: '2048'
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: '2048'
  name: '2048'
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: 'service-2048'
              servicePort: 80
